
// Code generated by stanc v2.30.0
#include <stan/model/model_header.hpp>
namespace PyrTransport_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 147> locations_array__ = 
{" (found before start of program)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 121, column 4 to column 14)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 122, column 4 to column 14)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 123, column 4 to column 33)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 124, column 4 to column 33)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 125, column 4 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 131, column 3 to column 28)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 133, column 3 to column 69)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 134, column 3 to column 66)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 135, column 3 to column 32)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 136, column 3 to column 32)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 137, column 3 to column 67)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 151, column 9 to column 12)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 151, column 2 to column 18)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 153, column 8 to column 11)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 153, column 12 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 153, column 2 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 154, column 8 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 154, column 14 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 154, column 16 to column 19)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 154, column 2 to column 31)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 157, column 3 to column 24)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 158, column 3 to column 24)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 159, column 3 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 160, column 3 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 161, column 3 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 168, column 12 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 168, column 6 to column 27)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 169, column 12 to column 17)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 169, column 18 to column 21)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 169, column 6 to column 34)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 170, column 6 to column 49)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 171, column 12 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 171, column 16 to column 19)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 171, column 6 to column 32)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 172, column 13 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 172, column 6 to column 32)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 175, column 6 to column 14)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 178, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 186, column 9 to column 136)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 185, column 25 to line 187, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 185, column 6 to line 187, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 187, column 7 to column 8)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 189, column 9 to column 136)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 188, column 25 to line 190, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 188, column 6 to line 190, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 190, column 7 to column 8)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 192, column 9 to column 136)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 191, column 25 to line 193, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 191, column 6 to line 193, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 193, column 7 to column 8)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 197, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 199, column 9 to column 35)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 198, column 22 to line 200, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 198, column 6 to line 200, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 200, column 7 to column 8)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 203, column 12 to column 48)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 204, column 12 to column 48)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 205, column 12 to column 48)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 202, column 28 to line 208, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 202, column 6 to line 208, column 7)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 212, column 6 to column 84)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 215, column 6 to column 99)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 219, column 6 to column 100)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 166, column 17 to line 224, column 4)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 166, column 3 to line 224, column 4)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 89, column 4 to column 10)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 90, column 4 to column 14)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 91, column 12 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 91, column 4 to column 24)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 92, column 10 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 92, column 16 to column 17)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 92, column 4 to column 27)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 94, column 4 to column 14)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 95, column 12 to column 17)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 95, column 4 to column 29)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 96, column 12 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 96, column 4 to column 26)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 97, column 12 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 97, column 4 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 100, column 10 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 100, column 16 to column 17)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 100, column 18 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 100, column 4 to column 36)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 101, column 10 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 101, column 16 to column 17)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 101, column 18 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 101, column 4 to column 36)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 104, column 4 to column 12)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 105, column 10 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 105, column 15 to column 16)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 105, column 4 to column 26)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 106, column 12 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 106, column 4 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 111, column 4 to column 19)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 112, column 4 to column 16)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 113, column 4 to column 21)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 114, column 4 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 115, column 10 to column 13)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 115, column 14 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 115, column 4 to column 34)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 116, column 4 to column 17)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 131, column 9 to column 15)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 6, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 7, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 8, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 9, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 10, column 6 to column 24)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 13, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 15, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 16, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 17, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 19, column 6 to column 44)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 20, column 6 to column 62)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 21, column 6 to column 51)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 24, column 6 to column 21)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 3, column 82 to line 26, column 5)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 31, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 32, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 33, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 34, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 35, column 6 to column 24)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 38, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 40, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 41, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 42, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 44, column 6 to column 44)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 45, column 6 to column 62)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 46, column 6 to column 51)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 49, column 6 to column 21)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 28, column 81 to line 51, column 5)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 56, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 57, column 6 to column 25)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 58, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 59, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 60, column 6 to column 24)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 63, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 65, column 6 to column 23)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 66, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 67, column 6 to column 22)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 69, column 6 to column 44)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 70, column 6 to column 62)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 71, column 6 to column 51)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 74, column 6 to column 21)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 53, column 82 to line 76, column 5)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 80, column 6 to column 18)",
 " (in 'c:/IBECPostDocDrive/2024_01_16_NCvsKR/DataProcessingInference/BayesianInference/tmp/PyrTransport.stan', line 78, column 68 to line 82, column 5)"};

struct PyruvateHP_NMR_ODEs2_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  operator()(const T0__& t, const std::vector<T1__>& y,
             const std::vector<T2__>& p, const std::vector<T3__>& x_r,
             const std::vector<int>& x_i, std::ostream* pstream__) const;
};
struct PyruvateHP_NMR_ODEs4_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  operator()(const T0__& t, const std::vector<T1__>& y,
             const std::vector<T2__>& p, const std::vector<T3__>& x_r,
             const std::vector<int>& x_i, std::ostream* pstream__) const;
};
struct PyruvateHP_NMR_ODEs8_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  operator()(const T0__& t, const std::vector<T1__>& y,
             const std::vector<T2__>& p, const std::vector<T3__>& x_r,
             const std::vector<int>& x_i, std::ostream* pstream__) const;
};
struct SteadyState_functor__ {
  template <typename T0__, typename T1__, typename T2__,
            stan::require_all_t<stan::is_col_vector<T0__>,
                                stan::is_vt_not_complex<T0__>,
                                stan::is_col_vector<T1__>,
                                stan::is_vt_not_complex<T1__>,
                                stan::is_stan_scalar<T2__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>, T2__>, -1, 1>
  operator()(const T0__& init, const T1__& p, const std::vector<T2__>& x_r,
             const std::vector<int>& x_i, std::ostream* pstream__) const;
};

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  PyruvateHP_NMR_ODEs2(const T0__& t, const std::vector<T1__>& y,
                       const std::vector<T2__>& p,
                       const std::vector<T3__>& x_r,
                       const std::vector<int>& x_i, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ k_f1 = DUMMY_VAR__;
      current_statement__ = 103;
      k_f1 = (2 * stan::model::rvalue(p, "p", stan::model::index_uni(1)));
      local_scalar_t__ k_r1 = DUMMY_VAR__;
      current_statement__ = 104;
      k_r1 = (2 * stan::model::rvalue(p, "p", stan::model::index_uni(2)));
      local_scalar_t__ T1_P = DUMMY_VAR__;
      current_statement__ = 105;
      T1_P = stan::model::rvalue(p, "p", stan::model::index_uni(3));
      local_scalar_t__ T1_X = DUMMY_VAR__;
      current_statement__ = 106;
      T1_X = stan::model::rvalue(p, "p", stan::model::index_uni(4));
      local_scalar_t__ kin = DUMMY_VAR__;
      current_statement__ = 107;
      kin = (2 * stan::model::rvalue(p, "p", stan::model::index_uni(5)));
      std::vector<local_scalar_t__> dInd_dt =
         std::vector<local_scalar_t__>(3, DUMMY_VAR__);
      local_scalar_t__ Pout = DUMMY_VAR__;
      current_statement__ = 109;
      Pout = stan::model::rvalue(y, "y", stan::model::index_uni(1));
      local_scalar_t__ Php = DUMMY_VAR__;
      current_statement__ = 110;
      Php = stan::model::rvalue(y, "y", stan::model::index_uni(2));
      local_scalar_t__ Xhp = DUMMY_VAR__;
      current_statement__ = 111;
      Xhp = stan::model::rvalue(y, "y", stan::model::index_uni(3));
      current_statement__ = 112;
      stan::model::assign(dInd_dt, ((-Pout * kin) - (Pout / T1_P)),
        "assigning variable dInd_dt", stan::model::index_uni(1));
      current_statement__ = 113;
      stan::model::assign(dInd_dt,
        (((k_r1 * Xhp) - (((1 / T1_P) + k_f1) * Php)) + (Pout * kin)),
        "assigning variable dInd_dt", stan::model::index_uni(2));
      current_statement__ = 114;
      stan::model::assign(dInd_dt,
        ((k_f1 * Php) - (((1 / T1_X) + k_r1) * Xhp)),
        "assigning variable dInd_dt", stan::model::index_uni(3));
      current_statement__ = 115;
      return dInd_dt;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  PyruvateHP_NMR_ODEs4(const T0__& t, const std::vector<T1__>& y,
                       const std::vector<T2__>& p,
                       const std::vector<T3__>& x_r,
                       const std::vector<int>& x_i, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ k_f1 = DUMMY_VAR__;
      current_statement__ = 117;
      k_f1 = (4 * stan::model::rvalue(p, "p", stan::model::index_uni(1)));
      local_scalar_t__ k_r1 = DUMMY_VAR__;
      current_statement__ = 118;
      k_r1 = (4 * stan::model::rvalue(p, "p", stan::model::index_uni(2)));
      local_scalar_t__ T1_P = DUMMY_VAR__;
      current_statement__ = 119;
      T1_P = stan::model::rvalue(p, "p", stan::model::index_uni(3));
      local_scalar_t__ T1_X = DUMMY_VAR__;
      current_statement__ = 120;
      T1_X = stan::model::rvalue(p, "p", stan::model::index_uni(4));
      local_scalar_t__ kin = DUMMY_VAR__;
      current_statement__ = 121;
      kin = (4 * stan::model::rvalue(p, "p", stan::model::index_uni(5)));
      std::vector<local_scalar_t__> dInd_dt =
         std::vector<local_scalar_t__>(3, DUMMY_VAR__);
      local_scalar_t__ Pout = DUMMY_VAR__;
      current_statement__ = 123;
      Pout = stan::model::rvalue(y, "y", stan::model::index_uni(1));
      local_scalar_t__ Php = DUMMY_VAR__;
      current_statement__ = 124;
      Php = stan::model::rvalue(y, "y", stan::model::index_uni(2));
      local_scalar_t__ Xhp = DUMMY_VAR__;
      current_statement__ = 125;
      Xhp = stan::model::rvalue(y, "y", stan::model::index_uni(3));
      current_statement__ = 126;
      stan::model::assign(dInd_dt, ((-Pout * kin) - (Pout / T1_P)),
        "assigning variable dInd_dt", stan::model::index_uni(1));
      current_statement__ = 127;
      stan::model::assign(dInd_dt,
        (((k_r1 * Xhp) - (((1 / T1_P) + k_f1) * Php)) + (Pout * kin)),
        "assigning variable dInd_dt", stan::model::index_uni(2));
      current_statement__ = 128;
      stan::model::assign(dInd_dt,
        ((k_f1 * Php) - (((1 / T1_X) + k_r1) * Xhp)),
        "assigning variable dInd_dt", stan::model::index_uni(3));
      current_statement__ = 129;
      return dInd_dt;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  PyruvateHP_NMR_ODEs8(const T0__& t, const std::vector<T1__>& y,
                       const std::vector<T2__>& p,
                       const std::vector<T3__>& x_r,
                       const std::vector<int>& x_i, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ k_f1 = DUMMY_VAR__;
      current_statement__ = 131;
      k_f1 = (8 * stan::model::rvalue(p, "p", stan::model::index_uni(1)));
      local_scalar_t__ k_r1 = DUMMY_VAR__;
      current_statement__ = 132;
      k_r1 = (8 * stan::model::rvalue(p, "p", stan::model::index_uni(2)));
      local_scalar_t__ T1_P = DUMMY_VAR__;
      current_statement__ = 133;
      T1_P = stan::model::rvalue(p, "p", stan::model::index_uni(3));
      local_scalar_t__ T1_X = DUMMY_VAR__;
      current_statement__ = 134;
      T1_X = stan::model::rvalue(p, "p", stan::model::index_uni(4));
      local_scalar_t__ kin = DUMMY_VAR__;
      current_statement__ = 135;
      kin = (8 * stan::model::rvalue(p, "p", stan::model::index_uni(5)));
      std::vector<local_scalar_t__> dInd_dt =
         std::vector<local_scalar_t__>(3, DUMMY_VAR__);
      local_scalar_t__ Pout = DUMMY_VAR__;
      current_statement__ = 137;
      Pout = stan::model::rvalue(y, "y", stan::model::index_uni(1));
      local_scalar_t__ Php = DUMMY_VAR__;
      current_statement__ = 138;
      Php = stan::model::rvalue(y, "y", stan::model::index_uni(2));
      local_scalar_t__ Xhp = DUMMY_VAR__;
      current_statement__ = 139;
      Xhp = stan::model::rvalue(y, "y", stan::model::index_uni(3));
      current_statement__ = 140;
      stan::model::assign(dInd_dt, ((-Pout * kin) - (Pout / T1_P)),
        "assigning variable dInd_dt", stan::model::index_uni(1));
      current_statement__ = 141;
      stan::model::assign(dInd_dt,
        (((k_r1 * Xhp) - (((1 / T1_P) + k_f1) * Php)) + (Pout * kin)),
        "assigning variable dInd_dt", stan::model::index_uni(2));
      current_statement__ = 142;
      stan::model::assign(dInd_dt,
        ((k_f1 * Php) - (((1 / T1_X) + k_r1) * Xhp)),
        "assigning variable dInd_dt", stan::model::index_uni(3));
      current_statement__ = 143;
      return dInd_dt;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>, T2__>, -1, 1>
  SteadyState(const T0__& init_arg__, const T1__& p_arg__,
              const std::vector<T2__>& x_r, const std::vector<int>& x_i,
              std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<stan::base_type_t<T0__>,
                                 stan::base_type_t<T1__>, T2__>;
    int current_statement__ = 0; 
    const auto& init = stan::math::to_ref(init_arg__);
    const auto& p = stan::math::to_ref(p_arg__);
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      current_statement__ = 145;
      return init;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
PyruvateHP_NMR_ODEs2_functor__::operator()(const T0__& t,
                                           const std::vector<T1__>& y,
                                           const std::vector<T2__>& p,
                                           const std::vector<T3__>& x_r,
                                           const std::vector<int>& x_i,
                                           std::ostream* pstream__)  const
{
  return PyruvateHP_NMR_ODEs2(t, y, p, x_r, x_i, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
PyruvateHP_NMR_ODEs4_functor__::operator()(const T0__& t,
                                           const std::vector<T1__>& y,
                                           const std::vector<T2__>& p,
                                           const std::vector<T3__>& x_r,
                                           const std::vector<int>& x_i,
                                           std::ostream* pstream__)  const
{
  return PyruvateHP_NMR_ODEs4(t, y, p, x_r, x_i, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
PyruvateHP_NMR_ODEs8_functor__::operator()(const T0__& t,
                                           const std::vector<T1__>& y,
                                           const std::vector<T2__>& p,
                                           const std::vector<T3__>& x_r,
                                           const std::vector<int>& x_i,
                                           std::ostream* pstream__)  const
{
  return PyruvateHP_NMR_ODEs8(t, y, p, x_r, x_i, pstream__);
}

template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>, T2__>, -1, 1>
SteadyState_functor__::operator()(const T0__& init, const T1__& p,
                                  const std::vector<T2__>& x_r,
                                  const std::vector<int>& x_i,
                                  std::ostream* pstream__)  const
{
  return SteadyState(init, p, x_r, x_i, pstream__);
}


class PyrTransport_model final : public model_base_crtp<PyrTransport_model> {

 private:
  int m;
  int stslm;
  std::vector<std::vector<int>> stsl;
  std::vector<std::vector<int>> sts;
  int obser;
  std::vector<std::vector<int>> obSta;
  std::vector<std::vector<int>> ncells;
  std::vector<std::vector<int>> nts;
  std::vector<std::vector<std::vector<double>>> Means;
  std::vector<std::vector<std::vector<double>>> Erros;
  int tml;
  std::vector<std::vector<double>> ts;
  std::vector<std::vector<double>> Y0us;
  int nParms;
  int Neq;
  std::vector<int> x_i;
  std::vector<double> x_r;
  std::vector<std::vector<double>> ivss;
  double itp; 
  
 
 public:
  ~PyrTransport_model() { }
  
  inline std::string model_name() const final { return "PyrTransport_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.0", "stancflags = "};
  }
  
  
  PyrTransport_model(stan::io::var_context& context__,
                     unsigned int random_seed__ = 0,
                     std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "PyrTransport_model_namespace::PyrTransport_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 66;
      context__.validate_dims("data initialization","m","int",
           std::vector<size_t>{});
      m = std::numeric_limits<int>::min();
      
      
      current_statement__ = 66;
      m = context__.vals_i("m")[(1 - 1)];
      current_statement__ = 67;
      context__.validate_dims("data initialization","stslm","int",
           std::vector<size_t>{});
      stslm = std::numeric_limits<int>::min();
      
      
      current_statement__ = 67;
      stslm = context__.vals_i("stslm")[(1 - 1)];
      current_statement__ = 68;
      stan::math::validate_non_negative_index("stsl", "m", m);
      current_statement__ = 69;
      context__.validate_dims("data initialization","stsl","int",
           std::vector<size_t>{static_cast<size_t>(1),
            static_cast<size_t>(m)});
      stsl = 
        std::vector<std::vector<int>>(1, 
          std::vector<int>(m, std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> stsl_flat__;
        current_statement__ = 69;
        stsl_flat__ = context__.vals_i("stsl");
        current_statement__ = 69;
        pos__ = 1;
        current_statement__ = 69;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 69;
          for (int sym2__ = 1; sym2__ <= 1; ++sym2__) {
            current_statement__ = 69;
            stan::model::assign(stsl, stsl_flat__[(pos__ - 1)],
              "assigning variable stsl", stan::model::index_uni(sym2__),
                                           stan::model::index_uni(sym1__));
            current_statement__ = 69;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 70;
      stan::math::validate_non_negative_index("sts", "stslm", stslm);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("sts", "m", m);
      current_statement__ = 72;
      context__.validate_dims("data initialization","sts","int",
           std::vector<size_t>{static_cast<size_t>(stslm),
            static_cast<size_t>(m)});
      sts = 
        std::vector<std::vector<int>>(stslm, 
          std::vector<int>(m, std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> sts_flat__;
        current_statement__ = 72;
        sts_flat__ = context__.vals_i("sts");
        current_statement__ = 72;
        pos__ = 1;
        current_statement__ = 72;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 72;
          for (int sym2__ = 1; sym2__ <= stslm; ++sym2__) {
            current_statement__ = 72;
            stan::model::assign(sts, sts_flat__[(pos__ - 1)],
              "assigning variable sts", stan::model::index_uni(sym2__),
                                          stan::model::index_uni(sym1__));
            current_statement__ = 72;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 73;
      context__.validate_dims("data initialization","obser","int",
           std::vector<size_t>{});
      obser = std::numeric_limits<int>::min();
      
      
      current_statement__ = 73;
      obser = context__.vals_i("obser")[(1 - 1)];
      current_statement__ = 74;
      stan::math::validate_non_negative_index("obSta", "obser", obser);
      current_statement__ = 75;
      context__.validate_dims("data initialization","obSta","int",
           std::vector<size_t>{static_cast<size_t>(1),
            static_cast<size_t>(obser)});
      obSta = 
        std::vector<std::vector<int>>(1, 
          std::vector<int>(obser, std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> obSta_flat__;
        current_statement__ = 75;
        obSta_flat__ = context__.vals_i("obSta");
        current_statement__ = 75;
        pos__ = 1;
        current_statement__ = 75;
        for (int sym1__ = 1; sym1__ <= obser; ++sym1__) {
          current_statement__ = 75;
          for (int sym2__ = 1; sym2__ <= 1; ++sym2__) {
            current_statement__ = 75;
            stan::model::assign(obSta, obSta_flat__[(pos__ - 1)],
              "assigning variable obSta", stan::model::index_uni(sym2__),
                                            stan::model::index_uni(sym1__));
            current_statement__ = 75;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 76;
      stan::math::validate_non_negative_index("ncells", "m", m);
      current_statement__ = 77;
      context__.validate_dims("data initialization","ncells","int",
           std::vector<size_t>{static_cast<size_t>(1),
            static_cast<size_t>(m)});
      ncells = 
        std::vector<std::vector<int>>(1, 
          std::vector<int>(m, std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> ncells_flat__;
        current_statement__ = 77;
        ncells_flat__ = context__.vals_i("ncells");
        current_statement__ = 77;
        pos__ = 1;
        current_statement__ = 77;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 77;
          for (int sym2__ = 1; sym2__ <= 1; ++sym2__) {
            current_statement__ = 77;
            stan::model::assign(ncells, ncells_flat__[(pos__ - 1)],
              "assigning variable ncells", stan::model::index_uni(sym2__),
                                             stan::model::index_uni(sym1__));
            current_statement__ = 77;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 78;
      stan::math::validate_non_negative_index("nts", "m", m);
      current_statement__ = 79;
      context__.validate_dims("data initialization","nts","int",
           std::vector<size_t>{static_cast<size_t>(1),
            static_cast<size_t>(m)});
      nts = 
        std::vector<std::vector<int>>(1, 
          std::vector<int>(m, std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> nts_flat__;
        current_statement__ = 79;
        nts_flat__ = context__.vals_i("nts");
        current_statement__ = 79;
        pos__ = 1;
        current_statement__ = 79;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 79;
          for (int sym2__ = 1; sym2__ <= 1; ++sym2__) {
            current_statement__ = 79;
            stan::model::assign(nts, nts_flat__[(pos__ - 1)],
              "assigning variable nts", stan::model::index_uni(sym2__),
                                          stan::model::index_uni(sym1__));
            current_statement__ = 79;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 80;
      stan::math::validate_non_negative_index("Means", "stslm", stslm);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("Means", "m", m);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("Means", "obser", obser);
      current_statement__ = 83;
      context__.validate_dims("data initialization","Means","double",
           std::vector<size_t>{static_cast<size_t>(stslm),
            static_cast<size_t>(m), static_cast<size_t>(obser)});
      Means = 
        std::vector<std::vector<std::vector<double>>>(stslm, 
          std::vector<std::vector<double>>(m, 
            std::vector<double>(obser, 
              std::numeric_limits<double>::quiet_NaN())));
      
      
      {
        std::vector<local_scalar_t__> Means_flat__;
        current_statement__ = 83;
        Means_flat__ = context__.vals_r("Means");
        current_statement__ = 83;
        pos__ = 1;
        current_statement__ = 83;
        for (int sym1__ = 1; sym1__ <= obser; ++sym1__) {
          current_statement__ = 83;
          for (int sym2__ = 1; sym2__ <= m; ++sym2__) {
            current_statement__ = 83;
            for (int sym3__ = 1; sym3__ <= stslm; ++sym3__) {
              current_statement__ = 83;
              stan::model::assign(Means, Means_flat__[(pos__ - 1)],
                "assigning variable Means", stan::model::index_uni(sym3__),
                                              stan::model::index_uni(sym2__),
                                              stan::model::index_uni(sym1__));
              current_statement__ = 83;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 84;
      stan::math::validate_non_negative_index("Erros", "stslm", stslm);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("Erros", "m", m);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("Erros", "obser", obser);
      current_statement__ = 87;
      context__.validate_dims("data initialization","Erros","double",
           std::vector<size_t>{static_cast<size_t>(stslm),
            static_cast<size_t>(m), static_cast<size_t>(obser)});
      Erros = 
        std::vector<std::vector<std::vector<double>>>(stslm, 
          std::vector<std::vector<double>>(m, 
            std::vector<double>(obser, 
              std::numeric_limits<double>::quiet_NaN())));
      
      
      {
        std::vector<local_scalar_t__> Erros_flat__;
        current_statement__ = 87;
        Erros_flat__ = context__.vals_r("Erros");
        current_statement__ = 87;
        pos__ = 1;
        current_statement__ = 87;
        for (int sym1__ = 1; sym1__ <= obser; ++sym1__) {
          current_statement__ = 87;
          for (int sym2__ = 1; sym2__ <= m; ++sym2__) {
            current_statement__ = 87;
            for (int sym3__ = 1; sym3__ <= stslm; ++sym3__) {
              current_statement__ = 87;
              stan::model::assign(Erros, Erros_flat__[(pos__ - 1)],
                "assigning variable Erros", stan::model::index_uni(sym3__),
                                              stan::model::index_uni(sym2__),
                                              stan::model::index_uni(sym1__));
              current_statement__ = 87;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 88;
      context__.validate_dims("data initialization","tml","int",
           std::vector<size_t>{});
      tml = std::numeric_limits<int>::min();
      
      
      current_statement__ = 88;
      tml = context__.vals_i("tml")[(1 - 1)];
      current_statement__ = 89;
      stan::math::validate_non_negative_index("ts", "tml", tml);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("ts", "m", m);
      current_statement__ = 91;
      context__.validate_dims("data initialization","ts","double",
           std::vector<size_t>{static_cast<size_t>(tml),
            static_cast<size_t>(m)});
      ts = 
        std::vector<std::vector<double>>(tml, 
          std::vector<double>(m, std::numeric_limits<double>::quiet_NaN()));
      
      
      {
        std::vector<local_scalar_t__> ts_flat__;
        current_statement__ = 91;
        ts_flat__ = context__.vals_r("ts");
        current_statement__ = 91;
        pos__ = 1;
        current_statement__ = 91;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 91;
          for (int sym2__ = 1; sym2__ <= tml; ++sym2__) {
            current_statement__ = 91;
            stan::model::assign(ts, ts_flat__[(pos__ - 1)],
              "assigning variable ts", stan::model::index_uni(sym2__),
                                         stan::model::index_uni(sym1__));
            current_statement__ = 91;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 92;
      stan::math::validate_non_negative_index("Y0us", "m", m);
      current_statement__ = 93;
      context__.validate_dims("data initialization","Y0us","double",
           std::vector<size_t>{static_cast<size_t>(3),
            static_cast<size_t>(m)});
      Y0us = 
        std::vector<std::vector<double>>(3, 
          std::vector<double>(m, std::numeric_limits<double>::quiet_NaN()));
      
      
      {
        std::vector<local_scalar_t__> Y0us_flat__;
        current_statement__ = 93;
        Y0us_flat__ = context__.vals_r("Y0us");
        current_statement__ = 93;
        pos__ = 1;
        current_statement__ = 93;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 93;
          for (int sym2__ = 1; sym2__ <= 3; ++sym2__) {
            current_statement__ = 93;
            stan::model::assign(Y0us, Y0us_flat__[(pos__ - 1)],
              "assigning variable Y0us", stan::model::index_uni(sym2__),
                                           stan::model::index_uni(sym1__));
            current_statement__ = 93;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 94;
      nParms = std::numeric_limits<int>::min();
      
      
      current_statement__ = 94;
      nParms = 5;
      current_statement__ = 95;
      Neq = std::numeric_limits<int>::min();
      
      
      current_statement__ = 95;
      Neq = 3;
      current_statement__ = 96;
      x_i = std::vector<int>(0, std::numeric_limits<int>::min());
      
      
      current_statement__ = 97;
      x_r = std::vector<double>(0, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 98;
      stan::math::validate_non_negative_index("ivss", "Neq", Neq);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("ivss", "m", m);
      current_statement__ = 100;
      ivss = 
        std::vector<std::vector<double>>(Neq, 
          std::vector<double>(m, std::numeric_limits<double>::quiet_NaN()));
      
      
      current_statement__ = 100;
      stan::model::assign(ivss, Y0us, "assigning variable ivss");
      current_statement__ = 101;
      itp = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 101;
      itp = 0;
      current_statement__ = 102;
      stan::math::validate_non_negative_index("theta", "nParms", nParms);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "PyrTransport_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ k_f1 = DUMMY_VAR__;
      current_statement__ = 1;
      k_f1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ k_r1 = DUMMY_VAR__;
      current_statement__ = 2;
      k_r1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ T1_P = DUMMY_VAR__;
      current_statement__ = 3;
      T1_P = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
               -2, 2, lp__);
      local_scalar_t__ T1_X = DUMMY_VAR__;
      current_statement__ = 4;
      T1_X = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
               -2, 2, lp__);
      local_scalar_t__ kin = DUMMY_VAR__;
      current_statement__ = 5;
      kin = in__.template read<local_scalar_t__>();
      std::vector<local_scalar_t__> theta =
         std::vector<local_scalar_t__>(nParms, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(theta,
        (0.0009999 + (((k_f1 - -2) * (0.09999 - 0.0009999)) / (2 - -2))),
        "assigning variable theta", stan::model::index_uni(1));
      current_statement__ = 8;
      stan::model::assign(theta,
        (0.000789 + (((k_r1 - -2) * (0.0789 - 0.000789)) / (2 - -2))),
        "assigning variable theta", stan::model::index_uni(2));
      current_statement__ = 9;
      stan::model::assign(theta, ((T1_P * 5.12) + 51.21),
        "assigning variable theta", stan::model::index_uni(3));
      current_statement__ = 10;
      stan::model::assign(theta, ((T1_X * 8.34) + 41.73),
        "assigning variable theta", stan::model::index_uni(4));
      current_statement__ = 11;
      stan::model::assign(theta,
        (4.896e-5 + (((kin - -2) * (0.004896 - 4.896e-5)) / (2 - -2))),
        "assigning variable theta", stan::model::index_uni(5));
      {
        current_statement__ = 12;
        stan::math::validate_non_negative_index("ing", "Neq", Neq);
        Eigen::Matrix<local_scalar_t__, -1, 1> ing =
           Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(Neq, DUMMY_VAR__);
        current_statement__ = 14;
        stan::math::validate_non_negative_index("Y0", "Neq", Neq);
        current_statement__ = 15;
        stan::math::validate_non_negative_index("Y0", "m", m);
        std::vector<std::vector<local_scalar_t__>> Y0 =
           std::vector<std::vector<local_scalar_t__>>(Neq, 
             std::vector<local_scalar_t__>(m, DUMMY_VAR__));
        current_statement__ = 17;
        stan::math::validate_non_negative_index("yhat", "stslm", stslm);
        current_statement__ = 18;
        stan::math::validate_non_negative_index("yhat", "m", m);
        current_statement__ = 19;
        stan::math::validate_non_negative_index("yhat", "Neq", Neq);
        std::vector<std::vector<std::vector<local_scalar_t__>>> yhat =
           std::vector<std::vector<std::vector<local_scalar_t__>>>(stslm, 
             std::vector<std::vector<local_scalar_t__>>(m, 
               std::vector<local_scalar_t__>(Neq, DUMMY_VAR__)));
        current_statement__ = 21;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(k_f1, -2, 2));
        current_statement__ = 22;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(k_r1, -2, 2));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(T1_X, 0, 1));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(T1_P, 0, 1));
        current_statement__ = 25;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(kin, -2, 2));
        current_statement__ = 65;
        for (int j = 1; j <= m; ++j) {
          current_statement__ = 26;
          stan::math::validate_non_negative_index("ivst", "Neq", Neq);
          std::vector<local_scalar_t__> ivst =
             std::vector<local_scalar_t__>(Neq, DUMMY_VAR__);
          current_statement__ = 28;
          stan::math::validate_non_negative_index("y_hat", "tml + 1",
                                                  (tml + 1));
          current_statement__ = 29;
          stan::math::validate_non_negative_index("y_hat", "Neq", Neq);
          std::vector<std::vector<local_scalar_t__>> y_hat =
             std::vector<std::vector<local_scalar_t__>>((tml + 1), 
               std::vector<local_scalar_t__>(Neq, DUMMY_VAR__));
          int lts = std::numeric_limits<int>::min();
          current_statement__ = 31;
          lts = stan::math::num_elements(
                  stan::model::rvalue(ts, "ts",
                    stan::model::index_min_max(1, (stan::model::rvalue(nts,
                                                     "nts",
                                                     stan::model::index_uni(1),
                                                       stan::model::index_uni(j))
                                                    + 1)),
                      stan::model::index_uni(j)));
          current_statement__ = 32;
          stan::math::validate_non_negative_index("part1", "lts", lts);
          current_statement__ = 33;
          stan::math::validate_non_negative_index("part1", "Neq", Neq);
          std::vector<std::vector<local_scalar_t__>> part1 =
             std::vector<std::vector<local_scalar_t__>>(lts, 
               std::vector<local_scalar_t__>(Neq, DUMMY_VAR__));
          current_statement__ = 35;
          stan::math::validate_non_negative_index("yhatPyr", "stsl[1, j]",
                                                  stan::model::rvalue(stsl,
                                                    "stsl",
                                                    stan::model::index_uni(1),
                                                      stan::model::index_uni(j)));
          Eigen::Matrix<local_scalar_t__, -1, 1> yhatPyr =
             Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
               stan::model::rvalue(stsl, "stsl",
                 stan::model::index_uni(1), stan::model::index_uni(j)),
               DUMMY_VAR__);
          int q = std::numeric_limits<int>::min();
          current_statement__ = 37;
          q = 1;
          current_statement__ = 38;
          stan::model::assign(ivst,
            stan::model::rvalue(ivss, "ivss",
              stan::model::index_omni(), stan::model::index_uni(j)),
            "assigning variable ivst");
          current_statement__ = 41;
          if (stan::math::logical_eq(
                stan::model::rvalue(ncells, "ncells",
                  stan::model::index_uni(1), stan::model::index_uni(j)), 2)) {
            current_statement__ = 39;
            stan::model::assign(part1,
              stan::math::integrate_ode_bdf(PyruvateHP_NMR_ODEs2_functor__(),
                ivst, itp,
                stan::model::rvalue(ts, "ts",
                  stan::model::index_min_max(1, (stan::model::rvalue(nts,
                                                   "nts",
                                                   stan::model::index_uni(1),
                                                     stan::model::index_uni(j))
                                                  + 1)),
                    stan::model::index_uni(j)), theta, x_r, x_i, pstream__,
                1.0e-9, 1.0e-9, 1e7),
              "assigning variable part1", stan::model::index_min_max(1, 
                                            (stan::model::rvalue(nts, "nts",
                                               stan::model::index_uni(1),
                                                 stan::model::index_uni(j)) +
                                              1)), stan::model::index_omni());
          } 
          ;
          current_statement__ = 45;
          if (stan::math::logical_eq(
                stan::model::rvalue(ncells, "ncells",
                  stan::model::index_uni(1), stan::model::index_uni(j)), 4)) {
            current_statement__ = 43;
            stan::model::assign(part1,
              stan::math::integrate_ode_bdf(PyruvateHP_NMR_ODEs4_functor__(),
                ivst, itp,
                stan::model::rvalue(ts, "ts",
                  stan::model::index_min_max(1, (stan::model::rvalue(nts,
                                                   "nts",
                                                   stan::model::index_uni(1),
                                                     stan::model::index_uni(j))
                                                  + 1)),
                    stan::model::index_uni(j)), theta, x_r, x_i, pstream__,
                1.0e-9, 1.0e-9, 1e7),
              "assigning variable part1", stan::model::index_min_max(1, 
                                            (stan::model::rvalue(nts, "nts",
                                               stan::model::index_uni(1),
                                                 stan::model::index_uni(j)) +
                                              1)), stan::model::index_omni());
          } 
          ;
          current_statement__ = 49;
          if (stan::math::logical_eq(
                stan::model::rvalue(ncells, "ncells",
                  stan::model::index_uni(1), stan::model::index_uni(j)), 8)) {
            current_statement__ = 47;
            stan::model::assign(part1,
              stan::math::integrate_ode_bdf(PyruvateHP_NMR_ODEs8_functor__(),
                ivst, itp,
                stan::model::rvalue(ts, "ts",
                  stan::model::index_min_max(1, (stan::model::rvalue(nts,
                                                   "nts",
                                                   stan::model::index_uni(1),
                                                     stan::model::index_uni(j))
                                                  + 1)),
                    stan::model::index_uni(j)), theta, x_r, x_i, pstream__,
                1.0e-9, 1.0e-9, 1e7),
              "assigning variable part1", stan::model::index_min_max(1, 
                                            (stan::model::rvalue(nts, "nts",
                                               stan::model::index_uni(1),
                                                 stan::model::index_uni(j)) +
                                              1)), stan::model::index_omni());
          } 
          ;
          current_statement__ = 51;
          stan::model::assign(y_hat, ivst,
            "assigning variable y_hat", stan::model::index_uni(1),
                                          stan::model::index_omni());
          current_statement__ = 54;
          for (int y = 1; y <= lts; ++y) {
            current_statement__ = 52;
            stan::model::assign(y_hat,
              stan::model::rvalue(part1, "part1",
                stan::model::index_uni(y), stan::model::index_omni()),
              "assigning variable y_hat", stan::model::index_uni((y + 1)),
                                            stan::model::index_omni());
          }
          ;
          current_statement__ = 60;
          for (int t = 1;
               t <= stan::model::rvalue(stsl, "stsl",
                      stan::model::index_uni(1), stan::model::index_uni(j));
               ++t) {
            current_statement__ = 56;
            stan::model::assign(yhat,
              stan::model::rvalue(part1, "part1",
                stan::model::index_uni((stan::model::rvalue(sts, "sts",
                                          stan::model::index_uni(t),
                                            stan::model::index_uni(j)) + 1)),
                  stan::model::index_uni(1)),
              "assigning variable yhat", stan::model::index_uni(t),
                                           stan::model::index_uni(j),
                                           stan::model::index_uni(1));
            current_statement__ = 57;
            stan::model::assign(yhat,
              stan::model::rvalue(part1, "part1",
                stan::model::index_uni((stan::model::rvalue(sts, "sts",
                                          stan::model::index_uni(t),
                                            stan::model::index_uni(j)) + 1)),
                  stan::model::index_uni(2)),
              "assigning variable yhat", stan::model::index_uni(t),
                                           stan::model::index_uni(j),
                                           stan::model::index_uni(2));
            current_statement__ = 58;
            stan::model::assign(yhat,
              stan::model::rvalue(part1, "part1",
                stan::model::index_uni((stan::model::rvalue(sts, "sts",
                                          stan::model::index_uni(t),
                                            stan::model::index_uni(j)) + 1)),
                  stan::model::index_uni(3)),
              "assigning variable yhat", stan::model::index_uni(t),
                                           stan::model::index_uni(j),
                                           stan::model::index_uni(3));
          }
          current_statement__ = 61;
          stan::model::assign(yhatPyr,
            stan::math::add(
              stan::math::to_vector(
                stan::model::rvalue(yhat, "yhat",
                  stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                  "stsl",
                                                  stan::model::index_uni(1),
                                                    stan::model::index_uni(j))),
                    stan::model::index_uni(j), stan::model::index_uni(1))),
              stan::math::to_vector(
                stan::model::rvalue(yhat, "yhat",
                  stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                  "stsl",
                                                  stan::model::index_uni(1),
                                                    stan::model::index_uni(j))),
                    stan::model::index_uni(j), stan::model::index_uni(2)))),
            "assigning variable yhatPyr");
          current_statement__ = 62;
          lp_accum__.add(
            stan::math::normal_lpdf<false>(
              stan::model::rvalue(Means, "Means",
                stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                "stsl",
                                                stan::model::index_uni(1),
                                                  stan::model::index_uni(j))),
                  stan::model::index_uni(j), stan::model::index_uni(1)),
              stan::model::rvalue(yhatPyr, "yhatPyr",
                stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                "stsl",
                                                stan::model::index_uni(1),
                                                  stan::model::index_uni(j)))),
              stan::model::rvalue(Erros, "Erros",
                stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                "stsl",
                                                stan::model::index_uni(1),
                                                  stan::model::index_uni(j))),
                  stan::model::index_uni(j), stan::model::index_uni(1))));
          current_statement__ = 63;
          lp_accum__.add(
            stan::math::normal_lpdf<false>(
              stan::model::rvalue(Means, "Means",
                stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                "stsl",
                                                stan::model::index_uni(1),
                                                  stan::model::index_uni(j))),
                  stan::model::index_uni(j), stan::model::index_uni(2)),
              stan::model::rvalue(yhat, "yhat",
                stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                "stsl",
                                                stan::model::index_uni(1),
                                                  stan::model::index_uni(j))),
                  stan::model::index_uni(j), stan::model::index_uni(3)),
              stan::model::rvalue(Erros, "Erros",
                stan::model::index_min_max(1, stan::model::rvalue(stsl,
                                                "stsl",
                                                stan::model::index_uni(1),
                                                  stan::model::index_uni(j))),
                  stan::model::index_uni(j), stan::model::index_uni(2))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "PyrTransport_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double k_f1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      k_f1 = in__.template read<local_scalar_t__>();
      double k_r1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      k_r1 = in__.template read<local_scalar_t__>();
      double T1_P = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      T1_P = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
               -2, 2, lp__);
      double T1_X = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      T1_X = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
               -2, 2, lp__);
      double kin = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      kin = in__.template read<local_scalar_t__>();
      std::vector<double> theta =
         std::vector<double>(nParms, 
           std::numeric_limits<double>::quiet_NaN());
      out__.write(k_f1);
      out__.write(k_r1);
      out__.write(T1_P);
      out__.write(T1_X);
      out__.write(kin);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      stan::model::assign(theta,
        (0.0009999 + (((k_f1 - -2) * (0.09999 - 0.0009999)) / (2 - -2))),
        "assigning variable theta", stan::model::index_uni(1));
      current_statement__ = 8;
      stan::model::assign(theta,
        (0.000789 + (((k_r1 - -2) * (0.0789 - 0.000789)) / (2 - -2))),
        "assigning variable theta", stan::model::index_uni(2));
      current_statement__ = 9;
      stan::model::assign(theta, ((T1_P * 5.12) + 51.21),
        "assigning variable theta", stan::model::index_uni(3));
      current_statement__ = 10;
      stan::model::assign(theta, ((T1_X * 8.34) + 41.73),
        "assigning variable theta", stan::model::index_uni(4));
      current_statement__ = 11;
      stan::model::assign(theta,
        (4.896e-5 + (((kin - -2) * (0.004896 - 4.896e-5)) / (2 - -2))),
        "assigning variable theta", stan::model::index_uni(5));
      if (emit_transformed_parameters__) {
        out__.write(theta);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ k_f1 = DUMMY_VAR__;
      k_f1 = in__.read<local_scalar_t__>();
      out__.write(k_f1);
      local_scalar_t__ k_r1 = DUMMY_VAR__;
      k_r1 = in__.read<local_scalar_t__>();
      out__.write(k_r1);
      local_scalar_t__ T1_P = DUMMY_VAR__;
      T1_P = in__.read<local_scalar_t__>();
      out__.write_free_lub(-2, 2, T1_P);
      local_scalar_t__ T1_X = DUMMY_VAR__;
      T1_X = in__.read<local_scalar_t__>();
      out__.write_free_lub(-2, 2, T1_X);
      local_scalar_t__ kin = DUMMY_VAR__;
      kin = in__.read<local_scalar_t__>();
      out__.write(kin);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"k_f1", "k_r1", "T1_P", "T1_X", "kin",
      "theta"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(nParms)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "k_f1");
    param_names__.emplace_back(std::string() + "k_r1");
    param_names__.emplace_back(std::string() + "T1_P");
    param_names__.emplace_back(std::string() + "T1_X");
    param_names__.emplace_back(std::string() + "kin");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nParms; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "k_f1");
    param_names__.emplace_back(std::string() + "k_r1");
    param_names__.emplace_back(std::string() + "T1_P");
    param_names__.emplace_back(std::string() + "T1_X");
    param_names__.emplace_back(std::string() + "kin");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nParms; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"k_f1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_r1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T1_P\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T1_X\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"kin\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nParms) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"k_f1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_r1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T1_P\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T1_X\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"kin\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nParms) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + 1) + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * nParms;
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + 1) + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * nParms;
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 5> names__{"k_f1", "k_r1", "T1_P",
      "T1_X", "kin"};
      const std::array<Eigen::Index, 5> constrain_param_sizes__{1, 1, 
       1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } 
using stan_model = PyrTransport_model_namespace::PyrTransport_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return PyrTransport_model_namespace::profiles__;
}

#endif


